# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20170520_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='nazwa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='nip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='album',
            name='nowyklient',
            field=models.CharField(blank=True, choices=[('Nawozy', 'Nawozy'), ('Zboża', 'Zboża')], max_length=25),
        ),
        migrations.AddField(
            model_name='album',
            name='numerwizyty',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=25),
        ),
        migrations.AddField(
            model_name='album',
            name='sprzedaz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='zamowienie',
            field=models.BooleanField(default=False),
        ),
    ]
