# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170520_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nazwa',
            new_name='klient',
        ),
    ]
