# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-23 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0015_auto_20170520_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaklienta', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Raporty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.DateField(null=True)),
                ('godzinastart', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=2, verbose_name='Godzina rozpoczęcia')),
                ('godzinakoniec', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=2, verbose_name='Godzina zakończenia')),
                ('aktywnosc', models.CharField(blank=True, choices=[('Praca biurowa', 'Praca biurowa'), ('Wizyta', 'Wizyta'), ('Urlop', 'Urlop'), ('Choroba', 'Choroba')], max_length=25, verbose_name='Aktywność')),
                ('miejscowosc', models.CharField(blank=True, max_length=20, verbose_name='Miejscowość')),
                ('kodpocztowy', models.CharField(blank=True, max_length=6, verbose_name='Kod pocztowy')),
                ('is_favorite', models.BooleanField(default=False)),
                ('uwagi', models.TextField(blank=True, max_length=1000)),
                ('zakonczono', models.BooleanField(default=False, verbose_name='Zakończono')),
                ('nip', models.CharField(blank=True, max_length=25, verbose_name='NIP')),
                ('sprzedaz', models.BooleanField(default=False, verbose_name='Sprzedaż')),
                ('zamowienie', models.BooleanField(default=False, verbose_name='Zamówienie')),
                ('lunch', models.BooleanField(default=False, verbose_name='Lunch')),
                ('nowyklient', models.CharField(blank=True, choices=[('Nawozy', 'Nawozy'), ('Zboża', 'Zboża')], max_length=25, verbose_name='Nowy klient')),
                ('numerwizyty', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=25, verbose_name='Numer wizyty')),
                ('klient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.Klienci')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='aktywnosc',
            field=models.CharField(blank=True, choices=[('Praca biurowa', 'Praca biurowa'), ('Wizyta', 'Wizyta'), ('Urlop', 'Urlop'), ('Choroba', 'Choroba')], max_length=25, verbose_name='Aktywność'),
        ),
        migrations.AlterField(
            model_name='album',
            name='godzinakoniec',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=2, verbose_name='Godzina zakończenia'),
        ),
        migrations.AlterField(
            model_name='album',
            name='godzinastart',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], max_length=2, verbose_name='Godzina rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='album',
            name='klient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.Klienci'),
        ),
        migrations.AlterField(
            model_name='album',
            name='kodpocztowy',
            field=models.CharField(blank=True, max_length=6, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='album',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Lunch'),
        ),
        migrations.AlterField(
            model_name='album',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='album',
            name='nip',
            field=models.CharField(blank=True, max_length=25, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='album',
            name='nowyklient',
            field=models.CharField(blank=True, choices=[('Nawozy', 'Nawozy'), ('Zboża', 'Zboża')], max_length=25, verbose_name='Nowy klient'),
        ),
        migrations.AlterField(
            model_name='album',
            name='numerwizyty',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=25, verbose_name='Numer wizyty'),
        ),
        migrations.AlterField(
            model_name='album',
            name='sprzedaz',
            field=models.BooleanField(default=False, verbose_name='Sprzedaż'),
        ),
        migrations.AlterField(
            model_name='album',
            name='zakonczono',
            field=models.BooleanField(default=False, verbose_name='Zakończono'),
        ),
        migrations.AlterField(
            model_name='album',
            name='zamowienie',
            field=models.BooleanField(default=False, verbose_name='Zamówienie'),
        ),
    ]
