# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20170523_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='nip',
        ),
        migrations.AddField(
            model_name='klienci',
            name='nipklienta',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
