# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20170523_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raporty',
            name='nip',
        ),
        migrations.AlterField(
            model_name='raporty',
            name='zakonczono',
            field=models.BooleanField(default=True, verbose_name='Zakończono'),
        ),
    ]
