# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20170523_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='klienci',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klienci',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='klient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Klienci'),
        ),
    ]
