# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20170524_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nazwy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='klient',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='music.Klienci'),
        ),
        migrations.AlterField(
            model_name='raporty',
            name='klient',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='music.Klienci'),
        ),
    ]
