# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_czas'),
    ]

    operations = [
        migrations.AddField(
            model_name='czas',
            name='minutnik',
            field=models.TimeField(null=True),
        ),
    ]
