# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_czas_minutnik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='probny',
        ),
        migrations.AlterField(
            model_name='album',
            name='godzinakoniec',
            field=models.TimeField(blank=True, verbose_name='Godzina zakończenia'),
        ),
        migrations.AlterField(
            model_name='album',
            name='godzinastart',
            field=models.TimeField(blank=True, verbose_name='Godzina rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='raporty',
            name='godzinakoniec',
            field=models.TimeField(blank=True, verbose_name='Godzina zakończenia'),
        ),
        migrations.AlterField(
            model_name='raporty',
            name='godzinastart',
            field=models.TimeField(blank=True, verbose_name='Godzina rozpoczęcia'),
        ),
    ]
